---
title: "final_code"
author: "Connor Riordan"
date: "4/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(dplyr)
library(readxl)
library(janitor)
library(gt)
library(scales)
library(markdown)
library(usmap)
library(tidyr)
```

## Presidential Election Results by County 2000-2016

```{r}
pres_results <- read.csv("raw_data/countypres_2000-2016.csv") %>%
  clean_names() %>%
  select(! version)

pres_results <- pres_results %>%
  mutate(abb_county = paste0(county, ", ", state_po))

dat <- pres_results %>%
  filter(abb_county == "Autauga, AL" | abb_county == "Baldwin, AL")

dat %>%
  filter(year == 2000) %>%
  ggplot(aes(candidate, candidatevotes, fill = abb_county)) + 
  geom_bar(stat = "identity", position = position_dodge())

us_counties <- map_data("county")

us_counties

pres_results$region <- tolower(pres_results$state)

newdata <- vector()
for(i in unique(pres_results$state)){
  sub <- pres_results[pres_results$state == i, ]
  for(j in unique(sub$county)){
    sub2 <- sub[sub$county == j, ]
    sub2$candidate <- paste(gsub(' ', '_', sub2$candidate), sub2$year, sep = '_')
    out <- sub2$candidatevotes
    out <- c(i, j, sub2$candidatevotes)
    names(out) <- c('state', 'county', sub2$candidate)
    newdata <- rbind(newdata, out)
  }
}

newdata <- as.data.frame(newdata)
newdata[, 1:2] <- apply(newdata[, 1:2], 2, tolower)

colnames(us_counties)[5:6] <- c('state', 'county')

new_counties <- vector()

for(i in unique(us_counties$state)){
  sub <- us_counties[us_counties$state == i, ]
  for(j in unique(sub$county)){
    sub2 <- sub[sub$county == j, c(1:4)]
    out <- c(i, j, as.list(sub2))
    new_counties <- rbind(new_counties, out)
  }
}

new_counties <- as.data.frame(new_counties)
colnames(new_counties)[1:2] <- c('state', 'county')

newtest <- merge.data.frame(newdata, new_counties, by = c('state', 'county'))
```

```{r}
pres_results_reg <- pres_results %>%
  select(! c(candidate, party, candidatevotes)) %>%
  filter(year == 2016) %>%
  group_by(county, year) %>% 
  summarise_all(funs(trimws(paste(., collapse = ''))))

```

## Income by County

```{r}
income_county <- read_excel("raw_data/per_capita_income_by_county.xlsx") %>%
  clean_names()

income_county <- income_county %>%
  rename(
    "county" = table_1_per_capita_personal_income_by_county_2016_2018,
    "personal_income_2016" = x2,
    "personal_income_2017" = x3,
    "personal_income_2018" = x4,
    "personal_income_rank_state_2018" = x5,
    "pct_change_2017" = x6,
    "pct_change_2018" = x7,
    "rank_in_state_pct_change" = x8
  )

income_county <- income_county[6:3223, 1:5]

income_county
  



```


```{r, join}



full_join(pres_results, income_county, by = county)

```

## Health Data (2016)

```{r}
health <- read.csv("raw_data/health_data_2016.csv") %>%
  clean_names() %>%
  select(! 3:6)



```

## State Education Data 2018

```{r}

education <- read.csv("raw_data/state_education_data_2018.csv") %>%
  clean_names() %>%
  select(! 3:7)

# sapply(education, numeric)

education$school_digger_number_of_stars_elementary <- as.numeric(education$school_digger_number_of_stars_elementary)
education$school_digger_number_of_stars_high <- as.numeric(education$school_digger_number_of_stars_high)
education$school_digger_number_of_stars_middle <- as.numeric(education$school_digger_number_of_stars_middle)
education$school_digger_rank_elementary <- as.numeric(education$school_digger_rank_elementary)
education$school_digger_rank_high <- as.numeric(education$school_digger_rank_high)
education$school_digger_rank_middle <- as.numeric(education$school_digger_rank_middle)
education$school_digger_rank_of_elementary <- as.numeric(education$school_digger_rank_of_elementary)
education$school_digger_rank_of_high <- as.numeric(education$school_digger_rank_of_high)
education$school_digger_rank_of_middle <- as.numeric(education$school_digger_rank_of_middle)
education$number_of_all_students_no_value_means_redacted <- as.numeric(education$number_of_all_students_no_value_means_redacted)

education <- education[2:52,]
education %>% filter(qualifying_name == "Connecticut") %>%
ggplot(aes(qualifying_name, school_digger_number_of_stars_elementary)) + geom_col()

```

## Family Voting Registration by Age and Income 2016

```{r}

age_income_2016_n <- read_excel("raw_data/family_voting_registration_by_age_and_income_2016.xlsx", skip = 5, col_types = "numeric") %>%
  clean_names() %>%
  select(! c(x1, x2))

age_income_2016_c <- read_excel("raw_data/family_voting_registration_by_age_and_income_2016.xlsx", skip = 5) %>%
  clean_names() %>%
  select(c(x1, x2))

age_income_2016 <- cbind(age_income_2016_c, age_income_2016_n)

age_income_2016 <- age_income_2016 %>%
  rename(
    "age_group" = x1,
    "total_income" = x2,
    "total_population" = x3,
    "reported_registered" = reported_registered_5,
    "reported_registered_percent" = x6,
    "reported_not_registered_percent" = x8,
    "no_response_to_registration" = no_response_to_registration1,
    "no_response_to_registration_percent" = x10,
    "reported_voted" = reported_voted_11,
    "reported_voted_percent" = x12,
    "reported_not_voted_percent" = x14,
    "no_response_to_voting" = no_response_to_voting2,
    "no_response_to_voting_percent" = x16,
    "registered_total_percent" = reported_registered_17,
    "voted_total_percent" = reported_voted_18
  )
age_income_2016_18_over <- age_income_2016 %>%
  head(13) %>%
  select(! age_group) %>%
  drop_na()

age_income_2016_18_24 <- age_income_2016[14:25,] %>%
  select(! age_group) %>%
  drop_na()

age_income_2016_25_44 <- age_income_2016[26:37,] %>%
  select(! age_group) %>%
  drop_na()

age_income_2016_45_64 <- age_income_2016[38:49,] %>%
  select(! age_group) %>%
  drop_na()

age_income_2016_65_74 <- age_income_2016[50:61,] %>%
  select(! age_group) %>%
  drop_na()

age_income_2016_75_over <- age_income_2016[62:73,] %>%
  select(! age_group) %>%
  drop_na()

age_income_2016_clean <- age_income_2016[2:166, 2:18]
  
```

```{r, bind}

cbind(pres_results, age_income_2016_clean)

```















